###############################################################
#
# MAKEFILE FOR CSTOOL
#
###############################################################


mex:

# NOTE generating the tags file requires MATLAB tags extension for vim
tags:
	ctags -R *.m
