function imHist = gui_genImHist(varargin)
% GUI_GENIMHIST
% Generate image histogram for csToolGUI. 
% This function generates the image histogram for a frame in csToolGUI. The function
% can produce histograms for full images (default) or for regions of an image using
% the 'region', region name/value argument. Model histograms should be generated by
% the csSegementer object in the csToolGUI.
% Note that only one of fh or image is required. If the image is not available in the
% calling context, but a frame handle is, then use 'fh',fh and gui_genImHist() will
% read the image in from the frame handles 'filename' property. If the image has been
% read in the caller already, then the image can be passed directly with a 'img' 
% tag in front.
%
% ARGUMENTS:
% 'fh', fh         - Frame handle of image to generate histogram for
% 'img', img       - Image to generate histogram for
% 'region', region - (Optional) Generate histogram for the region specified by region.
% 'nbins', N       - Set the number of bins to N
% 'fpgaMode'       - Use naive histogram method in $CSTOOL_DIR/util (slow)
% 

% Stefan Wong 2013

	%Set internal constants
	FPGA_MODE = 0;
	DEBUG     = 0;
	N_BINS    = 16;

	if(~isempty(varargin))
		for k = 1:length(varargin)
			if(ischar(varargin{k}))
				if(strncmpi(varargin{k}, 'fh', 2))
					fh = varargin{k+1};
				elseif(strncmpi(varargin{k}, 'img', 3))
					img = varargin{k+1};
				elseif(strncmpi(varargin{k}, 'region', 6))
					region = varargin{k+1};
				elseif(strncmpi(varargin{k}, 'nbins', 5))
					N_BINS = varargin{k+1};
				elseif(strncmpi(varargin{k}, 'fpga', 4))
					FPGA_MODE = 1;
				elseif(strncmpi(varargin{k}, 'debug', 5))
					DEBUG = 1;
				
				end
			end
		end
	end

	%Check for not enough args
	if(~exist('fh', 'var') && ~exist('img', 'var'))
		fprintf('ERROR: No fh or img data passed in\n');
		ihist = zeros(1, N_BINS);
		return;
	end
	%Check for too many args
	if(exist('fh', 'var') && exist('img', 'var'))
		fprintf('WARNING: Both img and fh passed in, using img...\n')
	else
		img = imread(get(fh, 'filename'), 'tif');
	end
	if(FPGA_MODE)
		fprintf('UNDER DEVELOPMENT (use util/gen_fpgaHist())\n');
		ihist = zeros(1,N_BINS);
	else
		ihist = hist(img, N_BINS);
	end
	
end 	%gui_genImHist()
