function bufDiskWrite(FB, fh, filename)
% BUFDISKWRITE
% bufDiskWrite(FB, fh, filename)
%
% Write frame handle data to disk
%
% ARGUMENTS:
% FB       - csFrameBuffer object
% fh       - Frame handle to write to disk
% filename - Name of *.mat file to store data for frame fh
%
% OUTPUTS:
% status   - -1 if file write error, otherwise 0
%

% Stefan Wong 2013

	frameStruct = struct('img', get(fh, 'img'), ...
		                 'bpImg', get(fh, 'bpimg'), ...
		                 'bpVec', get(fh, 'bpVec'), ...
		                 'bpSum', get(fh, 'bpSum'), ...
		                 'rhist', get(fh, 'rhist'), ...
		                 'ihist', get(fh, 'ihist'), ...
		                 'winParams', get(fh, 'winParams'), ...
		                 'winInit', get(fh, 'winInit'), ...
		                 'moments', {get(fh, 'moments')}, ...
		                 'nIters', get(fh, 'nIters'), ...
		                 'tVec', get(fh, 'tVec'), ...
		                 'dims', get(fh, 'dims'), ...
		                 'isSparse', get(fh, 'isSparse'), ...
		                 'filename', get(fh, 'filename'), ...
		                 'method', get(fh, 'method') ); %#ok

	save(filename, 'frameStruct');



end 	%bufDiskWrite()
